name: typed_event_bus
description: Event bus for your app with extended types feature
version: 1.0.0
homepage: https://github.com/iadept/typed_event_bus
repository: https://github.com/iadept/typed_event_bus

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: