name: typed_event_bus
description: Event bus for your app with extended types feature
version: 1.1.1
homepage: https://github.com/iadept/typed_event_bus
repository: https://github.com/iadept/typed_event_bus

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.16.0
